# Generated by Django 5.2.1 on 2025-05-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
